LPE/ViewWebMvc/Controllers/RelatorioManagerController.cs
using System;
using System.Web.Script.Serialization;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Negocio;
using Modelo;
using Core.Serialization;

namespace ViewWebMvc.Controllers
{
    public class RelatorioManagerController : Controller
    {
        RelatorioBll negocio;
        ResultadoBll bllResultado;

        public RelatorioManagerController()
        {
            negocio = new RelatorioBll();
            bllResultado = new ResultadoBll();
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            return View();
        }

        public string ListResult()
        {
            List<Resultado> listaResultado;
            try
            {
                listaResultado = bllResultado.ListarResultadosSemPdf();
            }
            catch (Exception e)
            {
                TempData["ErrorMessage"] = "Ocorreu um erro na requisição dos resultados.";
                throw e;
            }

            JavaScriptSerializer serializer = JsDateTimeSerializer.GetSerializer();
            return serializer.Serialize(listaResultado.Select(p => new { p.IdResultado,
                                                                         p.IdQuestionario.NomeQuestionario, 
                                                                         p.IdUsuario.Pessoa_Usuario.NomePessoa,
                                                                         p.IdUsuario.Pessoa_Usuario.SobrenomePessoa,
                                                                         p.IdRelatorio.IdRelatorio,
                                                                         p.Valor,
                                                                         p.IdRelatorio.IdGrupo.NomeGrupo
                                                                        }));
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult CreateAndUpdate()
        {
            return PartialView();
        }

        [HttpPost]
        public string Create(FormCollection collection)
        {
            try
            {
                //validateParameterList(ProductForm);
                Relatorio entity = new Relatorio
                {
                    IdGrupo = new RelatorioGrupo { IdGrupo = Convert.ToInt32(collection["Grupo[]"])},
                    //Nivel 4 - Sem classificação. Alterar caso o resultado seja feito por nivel de porcentagem (Acima, Medio ou Abaixo)
                    IdNivel = 4, //new QuestaoGrupo { IdGrupo = Convert.ToInt32(collection["Grupo[]"]) },
                    Caracteristica = collection["Caracteristica"],
                    Motiva = collection["Motiva"],
                    Desagrada = collection["Desagrada"],
                    Potencial = collection["Potencial"],
                    ValorMin = Convert.ToDouble(collection["ValorMin"]),
                    ValorMax = Convert.ToDouble(collection["ValorMax"]),
                    UsuarioInclusao = Session["user"].ToString()
                };

                negocio.Inserir(entity);
            }
            catch (Exception e)
            {
                TempData["ErrorMessage"] = "Ocorreu um erro no cadastro do endereço.";
                throw e;
            }

            return "True";
        }

        [HttpPost]
        public string Update(FormCollection collection)
        {
            try
            {
                //validateParameterList(ProductForm);

                Relatorio entity = new Relatorio
                {
                    IdRelatorio = Convert.ToInt32(collection["id"]),
                    IdGrupo = new RelatorioGrupo { IdGrupo = Convert.ToInt32(collection["GrupoRel[]"]) },
                    //Nivel 4 - Sem classificação. Alterar caso o resultado seja feito por nivel de porcentagem (Acima, Medio ou Abaixo)
                    IdNivel = 4, //new QuestaoGrupo { IdGrupo = Convert.ToInt32(collection["Grupo[]"]) },
                    Caracteristica = collection["Caracteristica"],
                    Motiva = collection["Motiva"],
                    Desagrada = collection["Desagrada"],
                    Potencial = collection["Potencial"],
                    ValorMin = Convert.ToDouble(collection["ValorMin"]),
                    ValorMax = Convert.ToDouble(collection["ValorMax"]),
                    UsuarioAteracao = Session["user"].ToString()
                };

                negocio.Alterar(entity);
            }
            catch (Exception e)
            {
                TempData["ErrorMessage"] = "Ocorreu um erro na alteraçao do endereço.";
                throw e;
            }

            return "True";
        }

        public string Search(string id)
        {
            Relatorio entity;

            int idRelatorio = Convert.ToInt32(id);
            try
            {
                entity = negocio.Consultar(idRelatorio);
            }

            catch (Exception e)
            {
                TempData["ErrorMessage"] = "Ocorreu um erro na requisição do endereço.";
                throw e;
            }

            Relatorio newEntity = new Relatorio
            {
                IdGrupo = entity.IdGrupo,
                //Nivel 4 - Sem classificação. Alterar caso o resultado seja feito por nivel de porcentagem (Acima, Medio ou Abaixo)
                IdNivel = 4, //new QuestaoGrupo { IdGrupo = Convert.ToInt32(collection["Grupo[]"]) },
                Caracteristica = entity.Caracteristica,
                Motiva = entity.Motiva,
                Desagrada = entity.Desagrada,
                Potencial = entity.Potencial,
                ValorMin = entity.ValorMin,
                ValorMax = entity.ValorMax
            };

            JavaScriptSerializer serializer = JsDateTimeSerializer.GetSerializer();
            string json = serializer.Serialize(newEntity);
            return json;

            //return "teste";
        }

        [HttpPost]
        public bool Delete(int id)
        {
            try
            {
                Relatorio entidade = negocio.Consultar(id);
                negocio.ExcluirLogico(entidade);
            }

            catch (Exception e)
            {
                TempData["ErrorMessage"] = "Ocorreu um erro na remoção do Endereço.";
                throw e;
            }
            return true;
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Details(int id)
        {
            Relatorio entidade = negocio.Consultar(id);
            return View(entidade);
        }
    }
}

LPE/ViewWebMvc/Controllers/ResultadoManagerController.cs
using System;
using System.Web.Script.Serialization;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using System.Net;
using Negocio;
using Modelo;
using Core.Serialization;
using iTextSharp;
using iTextSharp.text;
using iTextSharp.text.pdf;
using iTextSharp.text.html.simpleparser;

namespace ViewWebMvc.Controllers
{
    public class ResultadoManagerController : PDFController
    {
        ResultadoBll negocio;

        public ResultadoManagerController()
        {
            negocio = new ResultadoBll();
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            return View();
        }

        public string List()
        {
            List<Resultado> listaResultado;
            try
            {
                listaResultado = negocio.ListarAtivos();
            }
            catch (Exception e)
            {
                TempData["ErrorMessage"] = "Ocorreu um erro na requisição de endereços.";
                throw e;
            }

            JavaScriptSerializer serializer = JsDateTimeSerializer.GetSerializer();
            return serializer.Serialize(listaResultado.Select(p => new {
                                                                            p.IdResultado,
                                                                            p.IdQuestionario.NomeQuestionario,
                                                                            p.IdUsuario.Pessoa_Usuario.NomePessoa,
                                                                            p.IdUsuario.Pessoa_Usuario.SobrenomePessoa,
                                                                            p.IdRelatorio.IdRelatorio,
                                                                            p.Valor,
                                                                            p.IdRelatorio.IdGrupo.NomeGrupo
                                                                        }));
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult CreateAndUpdate()
        {
            return PartialView();
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult ViewResult()
        {
            return PartialView();
        }

        [HttpPost]
        public string Create(FormCollection collection)
        {
            try
            {
                //validateParameterList(ProductForm);
                //Resultado entity = new Resultado
                //{
                //    NomeResultado = collection["NomeResultado"],
                //    SobrenomeResultado = collection["SobrenomeResultado"],
                //    SexoResultado = Convert.ToChar(collection["SexoResultado"]),
                //    TratamentoResultado = "Sr(a).",
                //    IdEstadoCivil = new EstadoCivil { IdEstadoCivil = Convert.ToInt32(collection["EstadoCivil[]"]) },
                //    CPFResultado = collection["CPFResultado"],
                //    EmailResultado = collection["EmailResultado"],
                //    IdadeResultado = Convert.ToInt32(collection["IdadeResultado"]),
                //    DtNascimentoResultado = Convert.ToDateTime(collection["Ano"] + "/" + collection["Mes"] + "/" + collection["Dia"]),
                //    idEndereco = new Endereco { IdEndereco = Convert.ToInt32(collection["Endereco[]"]) },
                //    IdEscolaridade = new Escolaridade { IdEscolaridade = Convert.ToInt32(collection["Escolaridade[]"]) },
                //    IdProfissao = new CBOSinonimos { IdCBOSinonimo = Convert.ToInt32(collection["Profissao[]"]) }
                //};

                //negocio.Inserir(entity);
            }
            catch (Exception e)
            {
                TempData["ErrorMessage"] = "Ocorreu um erro no cadastro do endereço.";
                throw e;
            }

            return "True";
        }

        [HttpPost]
        public string Update(FormCollection collection)
        {
            try
            {
                //validateParameterList(ProductForm);

                //Resultado entity = new Resultado
                //{
                //    IdResultado = Convert.ToInt32(collection["id"]),
                //    NomeResultado = collection["NomeResultado"],
                //    SobrenomeResultado = collection["SobrenomeResultado"],
                //    SexoResultado = Convert.ToChar(collection["SexoResultado"]),
                //    TratamentoResultado = "Sr(a).",
                //    IdEstadoCivil = new EstadoCivil { IdEstadoCivil = Convert.ToInt32(collection["EstadoCivil[]"]) },
                //    CPFResultado = collection["CPFResultado"],
                //    EmailResultado = collection["EmailResultado"],
                //    IdadeResultado = Convert.ToInt32(collection["IdadeResultado"]),
                //    DtNascimentoResultado = Convert.ToDateTime(collection["Ano"] + "/" + collection["Mes"] + "/" + collection["Dia"]),
                //    idEndereco = new Endereco { IdEndereco = Convert.ToInt32(collection["Endereco[]"]) },
                //    IdEscolaridade = new Escolaridade { IdEscolaridade = Convert.ToInt32(collection["Escolaridade[]"]) },
                //    IdProfissao = new CBOSinonimos { IdCBOSinonimo = Convert.ToInt32(collection["Profissao[]"]) }
                //};

                //negocio.Alterar(entity);
            }
            catch (Exception e)
            {
                TempData["ErrorMessage"] = "Ocorreu um erro na alteraçao do endereço.";
                throw e;
            }

            return "True";
        }

        //[HttpPost]
        public ActionResult UpdateSetPdf(int id)
        {
            
            try
            {
                //validateParameterList(ProductForm);

                Resultado entity = negocio.Consultar(id);
                entity.Pdf = true;

                negocio.Alterar(entity);

                JavaScriptSerializer serializer = JsDateTimeSerializer.GetSerializer();
                //return serializer.Serialize(entity);
                //return new RazorPDF.PdfResult(entity, "ViewResult");
                return ViewPdf(entity);
            }
            catch (Exception e)
            {
                TempData["ErrorMessage"] = "Ocorreu um erro na alteraçao do endereço.";
                throw e;
            }
        }

        public void GenderPdf()
        {
            Document document = new Document(PageSize.A4, 80, 50, 30, 65);
            try
            {
                //D:\\PdfTest\\my.pdf
                string link = Server.MapPath("~");
                PdfWriter.GetInstance(document, new FileStream(Server.MapPath("~/my.pdf"), FileMode.Create));

                //document header attributes
                document.AddAuthor("betterThanZero");
                document.AddCreationDate();
                document.AddProducer();
                document.AddCreator("MySampleCode.com");
                document.AddTitle("Demo for iText XMLWorker");

                document.Open();


                //WebClient wc = new WebClient();
                //string htmlText = wc.DownloadString("http://localhost:59500/my.html");
//                string htmlText = @"<!DOCTYPE HTML PUBLIC '-//W3C//DTD HTML 4.0 Transitional//EN'>
//                        <HTML>
//                         <HEAD>
//                          <TITLE> LPE </TITLE>
//                          <META http-equiv='Content-Type' content='text/html; charset=UTF-8' />
//                         </HEAD>
//
//                         <BODY style='background:"+Server.MapPath("~/LPE/Content/imgs/timbrado.jpg")+@";'width:2481px; height:3505px;'>
//	                        <div id='conteudo' style='border: 1px solid black; width: 2200px; height: 2700px; margin: 600px 200px;'>
//		                        <div id='dadosPessoais'>
//			                        RELATÓRIO
//
//			                        Nome: Paulo Henrique Neto
//			                        E-mail: paulo@bigodesign.com.br
//			                        Data de Nascimento: 24/11/1987 Idade: 25 anos Sexo: M
//			                        RG: 4479524 DGPC/GO CPF: 030.301.741-40 Escolaridade: Superior Completo
//			                        Profissão: Designer Gráfico Cidade onde reside: Ap. de Goiânia/GO Data da Avaliação: 05/08/13		
//		                        </div>
//		                        <div style='font-size: 24px; color: #5e3a60;'>
//			                        <div style='border: 0px solid black; background-image:url("+Server.MapPath("~/LPE/Content/imgs/bolaVerde.jpg")+@"; width: 19px; height: 19px; margin: 5px;'></div><p>Perfil</p>
//		                        </div>
//		                        <div id='PerfilPdf'></div>
//
//		                        <div class='formTitle'>
//			                        <div class='iconCirculo'></div><p>Caracteristica</p>
//		                        </div>
//		                        <div id='CaracteristicaPdf'></div>
//
//		                        <div class='formTitle'>
//			                        <div class='iconCirculo'></div><p>Motiva</p>
//		                        </div>
//		                        <div id='MotivaPdf'></div>
//
//		                        <div class='formTitle'>
//			                        <div class='iconCirculo'></div><p>Desagrada</p>
//		                        </div>
//		                        <div id='DesagradaPdf'></div>
//
//		                        <div class='formTitle'>
//			                        <div class='iconCirculo'></div><p>Potencial</p>
//		                        </div>
//		                        <div id='PotencialPdf'></div>
//	                        </div>
//                         </BODY>
//                        </HTML>";
//                //Response.Write(htmlText);
//                List<IElement> htmlarraylist = HTMLWorker.ParseToList(new StringReader(htmlText), null);

LPE/ViewWebMvc/Views/RelatorioManager/CreateAndUpdate.cshtml
<div id="_div" style="display: none;">
    <div id="boxEsquerda">
        <form id="addForm" name="addReport" action="" method="post">
            <div class="pageheader">
                <div class="iconCirculo small"></div>
                <div class="caminho"></div>
                <div id="action">
                    <input id="updateButton" type="button" class="btview" />
                    <input id="backButton" type="button" onclick="callBackButton('RelatorioManager','List')" class="btback" />
                </div>
            </div>
            <div class="formBody">
                <div id="graphs_div">
                    <div class="formTitle">
                        <div class="iconCirculo"></div><p>Gráfico (Resultado)</p>
                    </div>
                    <div id="distributorGroupR_div" style="width: 700px; height: 10px;"></div>
                </div>
                <div class="formTitle">
                    <div class="iconCirculo"></div><p>Formulário para geração do relatório</p>
                </div>
                <div class="formContent">
                    <div class="formField">
                        <label for="GrupoRel">Perfil</label>
                        <select id="GrupoRel" size="60" name="GrupoRel" title="Ex.: Conservador" required></select>

                        <label for="Caracteristica">Caracteristica</label>
                        <textarea id="Caracteristica" name="Caracteristica" rows="12" cols="89"></textarea>

                        <label for="Motiva">Motiva</label>
                        <textarea id="Motiva" name="Motiva" rows="12" cols="89"></textarea>

                        <label for="Desagrada">Desagrada</label>
                        <textarea id="Desagrada" name="Desagrada" rows="12" cols="89"></textarea>

                        <label for="Potencial">Potencial</label>
                        <textarea id="Potencial" name="Potencial" rows="12" cols="89"></textarea>
                    </div>

                    <div class="formField">
                        <label for="ValorMin">Valor Mínimo</label>
                        <input id="ValorMin" name="ValorMin" type="text" size="30" title="Ex.: 28" placeholder="Digite sua idade (somente números)"/>

                        <label for="ValorMax">Valor Máximo</label>
                        <input id="ValorMax" name="ValorMax" type="text" size="30" title="Ex.: 28" placeholder="Digite sua idade (somente números)"/>
                    </div>
                </div>
            </div>    
        </form>
    </div>
</div>
<div id="PdfContent">
    @{
        Html.RenderAction("ViewResult", "ResultadoManager");
    }
</div>
<script type="text/javascript">
    var currentID;

    $(document).ready(function () {
        $('#PdfContent').hide();
        
        $(".caminho").html($("#hidFolder").val() + ' > ' + $("#hidMenu").val());

        var validator = $("#addForm").validate({
            rules: {
                Nome: { required: true },
                CPF: { required: true }
                //selectEstado: { required: true }
            },
            errorElement: "div",
            wrapper: "div",  // a wrapper around the error message 
            errorPlacement: function (error, element) { errorCSS(error, element); },
            messages: {
                Nome: "O Nome do município deve ser preenchido.",
                CPF: "O Nome da UF deve ser preenchido."
                //selectEstado: "O Nome do estado deve ser preenchido."
            }
        });

        $("#GrupoRel").fcbkcomplete({
            json_url: 'AutoComplete.aspx/AutoCompleteModel.RelatorioGrupoComplete,AutoCompleteModel,RELATORIOS_GRUPOS,NOME,ID_GRUPO',
            cache: true,
            filter_case: false,
            filter_selected: true,
            height: 10,
            maxitems: 1,
            complete_text: "Digite o nome do grupo..."
        });
    });

    //Funçao retirada do CrudMenu.js por causa do preenchimento do fcbkcomplete para o updateform
    function setupUpdateForm(Controller, Action, id) {
        $.ajax({
            type: "post",
            url: Controller + "/" + Action,
            traditional: true,
            data: { 'id': id },
            success: function (data, text) {
                var entidade = eval("(" + data + ")");
                var grupo = entidade.IdGrupo;
                var usr = $("#hidIdUser").val();
                var quest = $("#hidIdQuest").val();

                fillFormWithHistoryObject(entidade);
                callresultData($("#hidIdQuest").val(), $("#hidIdUser").val());

                //for (var i = 0; i < estados.length; i++)
                $('#GrupoRel').trigger('addItem', [{ 'title': grupo.NomeGrupo, 'value': grupo.IdGrupo}]);
            }
        });
    }
    
    function callresultData(idQuest, idUser) {
        //var COD = $(id).val();
        var loading = '<img src="/LPE/Content/imgs/ajax-loader.gif" alt="Carregando..."/>';

        $("#distributorGroupR_div").append(loading);

        drawGraphic(idQuest, idUser, 'GerarGrafico', 'distributorGroupR_div');

        $("#distributorGroupR_div").height(400);

        $("#graphs_div").show();
    }

    function ViewResult(Param) {
        var array = Param.split(',');
        var Controller = array[0];
        var Action = array[1];
        var id = $('#hidIdResultado').val();

        $.ajax({
            type: "post",
            url: Controller + "/" + Action,
            traditional: true,
            data: { 'id': id },
            success: function (data, text) {
                var entidade = eval("(" + data + ")");
                $('#PerfilPdf').html(entidade.IdRelatorio.IdGrupo.NomeGrupo);
                $('#CaracteristicaPdf').html(entidade.IdRelatorio.Caracteristica);
                $('#MotivaPdf').html(entidade.IdRelatorio.Motiva);
                $('#DesagradaPdf').html(entidade.IdRelatorio.Desagrada);
                $('#PotencialPdf').html(entidade.IdRelatorio.Potencial);

                $('#PdfContent').show();
                $('#_div').hide();
            }
        });
    }
</script>

LPE/ViewWebMvc/Views/RelatorioManager/Index.cshtml
<div id="PartialContent">
    @{
        Html.RenderAction("CreateAndUpdate", "RelatorioManager");
        Session["Gerar"] = Request.QueryString["Gender"].Substring(0,1);
    }
</div>
<div id="Base">
    <div class="pageheader">
        <div class="iconCirculo small"></div>
        <div class="caminho"></div>
        <div id="action">
            <input type="button" id="updateButton" class="btMenu"/>
            <input type="button" id="addRowButton" onclick="callCreate('RelatorioManager','Create')" value="" class="btadd" />
            <input type="button" id="updateRowButton" onclick="fillHidden('IdResultado'); callUpdate('RelatorioManager','Update','IdRelatorio',ViewResult,'ResultadoManager,UpdateSetPdf');"  value="" class="btedit" />
            <input type="button" id="deleteRowButton" onclick="callDelete('RelatorioManager','Delete','IdRelatorio')" value="" class="btdel" />    
            @*<input id="backButton" type="button" value="Voltar" onclick="callBackButton('PessoaManager','List')" class="btback" />*@
            <input type="hidden" id="hidIdUser" value="" />
            <input type="hidden" id="hidIdQuest" value="" />
            <input type="hidden" id="hidIdResultado" value="" />
        </div>
    </div>
    <div id="search"></div>
    <table id="Grid"></table>
</div>

<script type="text/javascript" >
    $(document).ready(function () {
        createGrid();
        var Action = 'List';

        if (@Session["Gerar"] == '1')
            Action = 'ListResult';
        
        loadGrid('RelatorioManager', Action);
    });

    function fillHidden(selectField){
        var selected = jQuery("#Grid").jqGrid('getGridParam', 'selrow');
        if (selected != null) {
            var id = $('#Grid').jqGrid('getCell', selected, selectField);

            $.ajax({
            type: "post",
            url: "ResultadoManager/Search",
            traditional: true,
            data: { 'id': id },
            success: function (data, text) {
                var entidade = eval("(" + data + ")");
                //var quest = entidade.IdQuestionario.IdQuestionario;
                //var user = entidade.IdUsuario.IdUsuario;
                $('#hidIdUser').val(entidade.IdUsuario.IdUsuario);
                $('#hidIdQuest').val(entidade.IdQuestionario.IdQuestionario);
                $('#hidIdResultado').val(entidade.IdResultado);
                }
            });
        }
    }

    function createGrid() {
        $("#Grid").jqGrid({
            colNames: ['Código', 'Questionário', 'Nome', 'Sobrenome', 'Código do relatório', 'Maior percentual', 'Perfil'],
            colModel: [
            { name: 'IdResultado', index: 'IdResultado', width: 50, sorttype: "text" },
            { name: 'NomeQuestionario', index: 'NomeQuestionario', width: 100, sorttype: "text" },
            { name: 'NomePessoa', index: 'NomePessoa', width: 249, sorttype: "text" },
            { name: 'SobrenomePessoa', index: 'SobrenomePessoa', width: 249, sorttype: "double" },
            { name: 'IdRelatorio', index: 'IdRelatorio', width: 150, sorttype: "text" },
            { name: 'Valor', index: 'Valor', width: 150, sorttype: "double" },
            { name: 'NomeGrupo', index: 'NomeGrupo', width: 100, sorttype: "text" },
   	              ],
            datatype: "json",
            height: 'auto',
            caption: "Relatórios não gerados",
            sortorder: "asc",
            sortable: true,
            viewrecords: true,
            datatype: "local"
        });
    };
</script>