LPE/ViewWebMvc/Controllers/EstadoManagerController.cs
using System;
using System.Web.Script.Serialization;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Negocio;
using Modelo;
using Core.Serialization;

namespace ViewWebMvc.Controllers
{
    public class EstadoManagerController : Controller
    {
        EstadoBll negocio;

        public EstadoManagerController()
        {
            negocio = new EstadoBll();
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            return View();
        }

        public string List()
        {
            List<Estado> listaEstado;
            try
            {
                listaEstado = negocio.ListarAtivos();
            }
            catch (Exception e)
            {
                TempData["ErrorMessage"] = "Ocorreu um erro na requisição de ESTADOS.";
                throw e;
            }

            JavaScriptSerializer serializer = JsDateTimeSerializer.GetSerializer();
            return serializer.Serialize(listaEstado.Select(e => new { e.IdEstado, e.UF, e.NomeEstado }));
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult CreateAndUpdate()
        {
            return PartialView();
        }

        [HttpPost]
        public string Create(FormCollection collection)
        {
            try
            {
                //validateParameterList(ProductForm);
                Estado entity = new Estado
                {
                    UF = collection["UF"],
                    NomeEstado = collection["NomeEstado"]
                };

                negocio.Inserir(entity);
            }
            catch (Exception e)
            {
                TempData["ErrorMessage"] = "Ocorreu um erro no cadastro de ESTADOS.";
                throw e;
            }

            return "True";
        }

        [HttpPost]
        public string Update(FormCollection collection)
        {
            try
            {
                //validateParameterList(ProductForm);
                Estado entity = new Estado
                {
                    IdEstado = Convert.ToInt32(collection["id"]),
                    UF = collection["UF"],
                    NomeEstado = collection["NomeEstado"]
                };

                negocio.Alterar(entity);
            }
            catch (Exception e)
            {
                TempData["ErrorMessage"] = "Ocorreu um erro na alteraçao do ESTADO.";
                throw e;
            }

            return "True";
        }

        public string Search(string id)
        {
            Estado entity;

            int idEstado = Convert.ToInt32(id);
            try
            {
                entity = negocio.Consultar(idEstado);
            }

            catch (Exception e)
            {
                TempData["ErrorMessage"] = "Ocorreu um erro na requisição do ESTADO.";
                throw e;
            }

            Estado newEntity = new Estado
            {
                IdEstado = entity.IdEstado,
                UF = entity.UF,
                NomeEstado = entity.NomeEstado
            };

            JavaScriptSerializer serializer = JsDateTimeSerializer.GetSerializer();
            string json = serializer.Serialize(newEntity);
            return json;
        }

        [HttpPost]
        public bool Delete(int id)
        {
            try
            {
                Estado entidade = negocio.Consultar(id);
                negocio.ExcluirLogico(entidade);
            }

            catch (Exception e)
            {
                TempData["ErrorMessage"] = "Ocorreu um erro na remoção do ESTADO.";
                throw e;
            }
            return true;
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Details(int id)
        {
            Estado entidade = negocio.Consultar(id);
            return View(entidade);
        }
    }
}

LPE/ViewWebMvc/Views/EstadoManager/CreateAndUpdate.cshtml
<div id="_div" style="display: none;">
    <div id="boxEsquerda">
        <form id="addForm" name="add" action="" method="post">
        <div class="pageheader">
            <input id="updateButton" type="button" value="Gravar" class="btsave" />
            <input id="backButton" type="button" value="Voltar" onclick="callBackButton('EstadoManager','List')" class="btback" />
        </div>
        <fieldset>
            <legend>Formulário de Estado</legend>
            <label id= "UFLabel" for="UF">
                UF
            </label>
            <input id="UF" name="UF" type="text" size="60" placeholder="Digite o nome da UF" required/>
            <label for="NomeEstado">
                Nome do estado
            </label>
            <input id="NomeEstado" name="NomeEstado" type="text" size="60" placeholder="Digite o nome do Estado" required/>
        </fieldset>
        </form>
    </div>
</div>


<script type="text/javascript">
    var currentID;

    $(document).ready(function () {

        var validator = $("#addForm").validate({
            rules: {
                UF: { required: true },
                NomeEstado: { required: true }
            },
            errorElement: "div",
            wrapper: "div",  // a wrapper around the error message 
            errorPlacement: function (error, element) { errorCSS(error, element); },
            messages: {
                UF: "O Nome do UF não pode ser nulo.",
                NomeEstado: "O Nome do ESTADO não pode ser nulo."
            }
        });
    });

</script>

LPE/ViewWebMvc/Views/EstadoManager/Index.cshtml
<div id="PartialContent">
    @{
        Html.RenderAction("CreateAndUpdate", "EstadoManager");
    }
</div>
<div id="Base">
    <div class="pageheader">
        <input type="button" id="addRowButton" onclick="callCreate('EstadoManager','Create')" value="" class="btadd" />
        <input type="button" id="updateRowButton" onclick="callUpdate('EstadoManager','Update','IdEstado','List')" value="" class="btedit" />
        <input type="button" id="deleteRowButton" onclick="callDelete('EstadoManager','Delete','IdEstado')" value="" class="btdel" />
        <input type="button" id="menuButton" onclick="initializeOptionMenu('#conteudo');" value="" class="btback" />        
    </div>
    <div id="search"></div>
    <table id="Grid"></table>
</div>

<script type="text/javascript" >
    $(document).ready(function () {
        createGrid();
        loadGrid('EstadoManager', 'List');
    });

    function createGrid() {
        $("#Grid").jqGrid({
            colNames: ['Codigo', 'UF', 'Estado'],
            colModel: [
            { name: 'IdEstado', index: 'IdEstado', width: 50, sorttype: "text" },
            { name: 'UF', index: 'UF', width: 600, sorttype: "text" },
            { name: 'NomeEstado', index: 'NomeEstado', width: 600, sorttype: "text" },
   	              ],
            datatype: "json",
            height: 'auto',
            caption: "Estados cadastrados",
            sortorder: "asc",
            sortable: true,
            viewrecords: true,
            datatype: "local"
        });
    };

    function setupUpdateForm(Controller, Action, id) {
        $.ajax({
            type: "post",
            url: Controller + "/" + Action,
            traditional: true,
            data: { 'id': id },
            success: function (data, text) {
                var entidade = eval("(" + data + ")");

                fillFormWithObject(entidade);

            }
        });
    }
</script>