LPE/ViewWebMvc/Controllers/EscolaridadeManagerController.cs
using System;
using System.Web.Script.Serialization;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Negocio;
using Modelo;
using Core.Serialization;
using ViewWebMvc.Models;

namespace ViewWebMvc.Controllers
{
    public class EscolaridadeManagerController : Controller
    {
        EscolaridadeBll negocio;

        public EscolaridadeManagerController()
        {
            negocio = new EscolaridadeBll();
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            return View();
        }

        public string List()
        {
            List<Escolaridade> listaEscolaridade;
            try
            {
                listaEscolaridade = negocio.ListarAtivos();
            }
            catch (Exception e)
            {
                TempData["ErrorMessage"] = "Ocorreu um erro na requisição de endereços.";
                throw e;
            }

            JavaScriptSerializer serializer = JsDateTimeSerializer.GetSerializer();
            return serializer.Serialize(listaEscolaridade.Select(e => new { e.IdEscolaridade, e.IdNivelEscolaridadeEscolaridade.DescricaoNivelEscolaridade, e.DescricaoEscolaridade }));
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult CreateAndUpdate()
        {
            return PartialView();
        }

        [HttpPost]
        public string Create(FormCollection collection)
        {

            try
            {
                //validateParameterList(ProductForm);
                Escolaridade entity = new Escolaridade
                {
                    IdNivelEscolaridadeEscolaridade = new NivelEscolaridade { IdNivelEscolaridade = Convert.ToInt32(collection["selectNivel[]"]) },
                    DescricaoEscolaridade = collection["DescricaoEscolaridade"]
                };

                negocio.Inserir(entity);
            }
            catch (Exception e)
            {
                TempData["ErrorMessage"] = "Ocorreu um erro no cadastro da escolaridade.";
                throw e;
            }

            return "True";
        }

        [HttpPost]
        public string Update(FormCollection collection)
        {
            try
            {
                //validateParameterList(ProductForm);
                Escolaridade entity = new Escolaridade
                {
                    IdEscolaridade = Convert.ToInt32(collection["id"]),
                    IdNivelEscolaridadeEscolaridade = new NivelEscolaridade { IdNivelEscolaridade = Convert.ToInt32(collection["selectNivel[]"]) },
                    DescricaoEscolaridade = collection["DescricaoEscolaridade"]
                };

                negocio.Alterar(entity);
            }
            catch (Exception e)
            {
                TempData["ErrorMessage"] = "Ocorreu um erro na alteraçao da escolaridade.";
                throw e;
            }

            return "True";
        }

        public string Search(string id)
        {
            Escolaridade entity;

            int idEscolaridade = Convert.ToInt32(id);
            try
            {
                entity = negocio.Consultar(idEscolaridade);
            }

            catch (Exception e)
            {
                TempData["ErrorMessage"] = "Ocorreu um erro na requisição da escolaridade.";
                throw e;
            }

            EscolaridadeViewModel Address = new EscolaridadeViewModel
            {
                idEscolaridade = entity.IdEscolaridade,
                idNivelEscolaridade = entity.IdNivelEscolaridadeEscolaridade.IdNivelEscolaridade.ToString(),
                selectNivel = entity.IdNivelEscolaridadeEscolaridade.DescricaoNivelEscolaridade,
                DescricaoEscolaridade = entity.DescricaoEscolaridade
            };

            JavaScriptSerializer serializer = JsDateTimeSerializer.GetSerializer();
            string json = serializer.Serialize(Address);
            return json;
        }

        [HttpPost]
        public bool Delete(int id)
        {
            try
            {
                Escolaridade entidade = negocio.Consultar(id);
                negocio.ExcluirLogico(entidade);
            }

            catch (Exception e)
            {
                TempData["ErrorMessage"] = "Ocorreu um erro na remoção da escolaridade.";
                throw e;
            }
            return true;
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Details(int id)
        {
            Escolaridade entidade = negocio.Consultar(id);
            return View(entidade);
        }
    }
}

LPE/ViewWebMvc/Views/EscolaridadeManager/CreateAndUpdate.cshtml
<div id="_div" style="display: none;">
    <div id="boxEsquerda">
        <form id="addForm" name="add" action="" method="post">
        <div class="pageheader">
            <input id="updateButton" type="button" value="Gravar" class="btsave" />
            <input id="backButton" type="button" value="Voltar" onclick="callBackButton('EscolaridadeManager','List')" class="btback" />
        </div>
        <fieldset>
            <legend>Formulário de Escolaridade</legend>
            
            <label id= "DescricaoEscolaridadeLabel" for="DescricaoEscolaridade">Descrição</label>
            <input id="DescricaoEscolaridade" name="DescricaoEscolaridade" type="text" size="60" placeholder="Digite o nome da Escolaridade" required/>
            
            <label for="selectNivel[]">Nível da escolaridade</label>
            <select id="selectNivel" size="60" name="selectNivel[]" title="Ex.: São Paulo" placeholder="Digite o nome do municipio" required></select>

        </fieldset>
        </form>
    </div>
</div>


<script type="text/javascript">
    var currentID;

    $(document).ready(function () {

        var validator = $("#addForm").validate({
            rules: {
                DescricaoEscolaridade: { required: true },
                selectNivel: { required: true }
            },
            errorElement: "div",
            wrapper: "div",  // a wrapper around the error message 
            errorPlacement: function (error, element) { errorCSS(error, element); },
            messages: {
                DescricaoEscolaridade: "O Nome do LOGRADOURO não ficar em branco.",
                selectNivel: "O nome do MUNICIPIO não pode ficar em branco"
            }
        });

        $("#selectNivel").fcbkcomplete({
            json_url: 'AutoComplete.aspx/AutoCompleteModel.NivelEscolaridadeComplete,AutoCompleteModel,ESCOLARIDADE_NIVEL,DESCRICAO,ID_NIVEL_ESCOLARIDADE',
            cache: true,
            filter_case: false,
            filter_selected: true,
            height: 10,
            maxitems: 1,
            complete_text: "Digite um nível para a escolaridade..."
        });

    });

</script>

LPE/ViewWebMvc/Views/EscolaridadeManager/Index.cshtml
<div id="PartialContent">
    @{
        Html.RenderAction("CreateAndUpdate", "EscolaridadeManager");
    }
</div>
<div id="Base">
    <div class="pageheader">
        <input type="button" id="addRowButton" onclick="callCreate('EscolaridadeManager','Create')" value="" class="btadd" />
        <input type="button" id="updateRowButton" onclick="callUpdate('EscolaridadeManager','Update','IdEscolaridade','List')" value="" class="btedit" />
        <input type="button" id="deleteRowButton" onclick="callDelete('EscolaridadeManager','Delete','IdEscolaridade')" value="" class="btdel" />        
        <input type="button" id="menuButton" onclick="initializeOptionMenu('#conteudo');" value="" class="btback" />        
    </div>
    <div id="search"></div>
    <table id="Grid"></table>
</div>

<script type="text/javascript" >
    $(document).ready(function () {
        createGrid();
        loadGrid('EscolaridadeManager', 'List');
    });

    function createGrid() {
        $("#Grid").jqGrid({
            colNames: ['Codigo', 'Nível', 'Descrição'],
            colModel: [
            { name: 'IdEscolaridade', index: 'IdEscolaridade', width: 50, sorttype: "text" },
            { name: 'DescricaoNivelEscolaridade', index: 'DescricaoNivelEscolaridade', width: 249, sorttype: "text" },
            { name: 'DescricaoEscolaridade', index: 'DescricaoEscolaridade', width: 249, sorttype: "text" }
   	              ],
            datatype: "json",
            height: 'auto',
            caption: "Escolariadades Cadastradas",
            sortorder: "asc",
            sortable: true,
            viewrecords: true,
            datatype: "local"
        });
    };

    function setupUpdateForm(Controller, Action, id) {
        $.ajax({
            type: "post",
            url: Controller + "/" + Action,
            traditional: true,
            data: { 'id': id },
            success: function (data, text) {
                var entidade = eval("(" + data + ")");

                fillFormWithObject(entidade);

                $('#selectNivel').trigger('addItem', [{ 'title': entidade.selectNivel, 'value': entidade.idNivelEscolaridade}]);
            }
        });
    }
</script>